#!/bin/bash

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  🧪 How to Test Daily Subscription Renewal                     ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📝 STEP-BY-STEP GUIDE:"
echo ""
echo "1️⃣  Open your browser:"
echo "    → http://localhost:3000/support"
echo ""
echo "2️⃣  Find 'Test Denné' tier (at the top, yellow border):"
echo "    - Price: €1/deň"
echo "    - Badge: 🧪 TEST MODE"
echo "    - Features: Obnovuje sa každý deň"
echo ""
echo "3️⃣  Click 'Vybrať plán' button"
echo ""
echo "4️⃣  Enter test payment details:"
echo "    Card number: 4242 4242 4242 4242"
echo "    Expiry: Any future date (e.g., 12/26)"
echo "    CVC: Any 3 digits (e.g., 123)"
echo "    Name: Your name"
echo "    Email: Your email"
echo ""
echo "5️⃣  Complete payment"
echo "    → You'll be redirected to /thank-you"
echo ""
echo "6️⃣  Go to your account:"
echo "    → http://localhost:3000/account"
echo ""
echo "7️⃣  Find 'Active Subscription' section:"
echo "    You should see:"
echo "    - Plan: Test Daily"
echo "    - Price: €1/day"
echo "    - Status: Active"
echo "    - Renews on: [tomorrow's date]"
echo ""
echo "8️⃣  Look for subscription ID in one of these places:"
echo ""
echo "    A) In browser console (if debug logs enabled)"
echo "    B) In Stripe Dashboard:"
echo "       → https://dashboard.stripe.com/test/subscriptions"
echo "       → Click on the subscription"
echo "       → Copy ID from URL or page (starts with 'sub_1...')"
echo ""
echo "    C) Query database directly:"
echo "       psql or Supabase SQL Editor:"
echo ""
cat << 'SQL'
       SELECT 
         stripe_subscription_id,
         tier,
         status,
         current_period_end
       FROM subscriptions 
       WHERE tier = 'test_daily'
       ORDER BY created_at DESC
       LIMIT 1;
SQL
echo ""
echo "9️⃣  Copy the subscription ID (example: sub_1SQaZhKF1O52aJAIYkK0ZK7o)"
echo ""
echo "🔟 Run the test script:"
echo "    → ./test-daily-renewal.sh sub_1SQaZhKF1O52aJAIYkK0ZK7o"
echo "                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
echo "                              Replace with YOUR actual ID!"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "✅ EXPECTED RESULTS after running script:"
echo ""
echo "  • Server logs show:"
echo "    💰 Invoice paid for subscription: sub_xxx"
echo "    ✅ Subscription updated with new billing period"
echo ""
echo "  • /account page shows updated 'Renews on' date (+1 day)"
echo ""
echo "  • Database current_period_end is +1 day from before"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "🔁 TESTING MULTIPLE RENEWALS:"
echo ""
echo "  Run the script multiple times to simulate multiple days:"
echo ""
echo "  ./test-daily-renewal.sh sub_xxx  # Day 1 → Day 2"
echo "  ./test-daily-renewal.sh sub_xxx  # Day 2 → Day 3"
echo "  ./test-daily-renewal.sh sub_xxx  # Day 3 → Day 4"
echo ""
echo "  Each run advances the renewal date by 1 day!"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "❓ TROUBLESHOOTING:"
echo ""
echo "  Problem: Can't see 'Test Denné' tier"
echo "  → Dev server needs restart (Ctrl+C, then npm run dev)"
echo "  → Hard refresh browser (Cmd+Shift+R)"
echo ""
echo "  Problem: Payment fails"
echo "  → Check .env.local has STRIPE_PRICE_TEST_DAILY set"
echo "  → Check Stripe dashboard - product should exist"
echo ""
echo "  Problem: Script says 'subscription not found'"
echo "  → You used placeholder 'sub_YOUR_SUBSCRIPTION_ID'"
echo "  → Get real ID from step 8 above!"
echo ""
echo "  Problem: Webhook not received"
echo "  → Check Stripe CLI listener: ps aux | grep 'stripe listen'"
echo "  → Should see: PID 15794 (or similar)"
echo "  → If not running: stripe listen --forward-to localhost:3000/api/webhooks/stripe"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📚 MORE INFO:"
echo "  → Read: DAILY_SUBSCRIPTION_TESTING.md"
echo "  → Read: SUBSCRIPTION_RENEWAL_FLOW.md"
echo ""
echo "🚀 Ready? Start with Step 1 above!"
echo ""
